// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.24.0
// 	protoc        v3.10.0
// source: sortService.proto

package sortService

import (
	context "context"
	reflect "reflect"
	sync "sync"

	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// This is a compile-time assertion that a sufficiently up-to-date version
// of the legacy proto package is being used.
const _ = proto.ProtoPackageIsVersion4

type SortRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Nums []int32 `protobuf:"varint,1,rep,packed,name=nums,proto3" json:"nums,omitempty"`
}

func (x *SortRequest) Reset() {
	*x = SortRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_sortService_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SortRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SortRequest) ProtoMessage() {}

func (x *SortRequest) ProtoReflect() protoreflect.Message {
	mi := &file_sortService_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SortRequest.ProtoReflect.Descriptor instead.
func (*SortRequest) Descriptor() ([]byte, []int) {
	return file_sortService_proto_rawDescGZIP(), []int{0}
}

func (x *SortRequest) GetNums() []int32 {
	if x != nil {
		return x.Nums
	}
	return nil
}

type SortResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Nums []int32 `protobuf:"varint,1,rep,packed,name=nums,proto3" json:"nums,omitempty"`
}

func (x *SortResponse) Reset() {
	*x = SortResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_sortService_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SortResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SortResponse) ProtoMessage() {}

func (x *SortResponse) ProtoReflect() protoreflect.Message {
	mi := &file_sortService_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SortResponse.ProtoReflect.Descriptor instead.
func (*SortResponse) Descriptor() ([]byte, []int) {
	return file_sortService_proto_rawDescGZIP(), []int{1}
}

func (x *SortResponse) GetNums() []int32 {
	if x != nil {
		return x.Nums
	}
	return nil
}

var File_sortService_proto protoreflect.FileDescriptor

var file_sortService_proto_rawDesc = []byte{
	0x0a, 0x11, 0x73, 0x6f, 0x72, 0x74, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x12, 0x0b, 0x73, 0x6f, 0x72, 0x74, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65,
	0x22, 0x21, 0x0a, 0x0b, 0x53, 0x6f, 0x72, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12,
	0x12, 0x0a, 0x04, 0x6e, 0x75, 0x6d, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x05, 0x52, 0x04, 0x6e,
	0x75, 0x6d, 0x73, 0x22, 0x22, 0x0a, 0x0c, 0x53, 0x6f, 0x72, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f,
	0x6e, 0x73, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x75, 0x6d, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28,
	0x05, 0x52, 0x04, 0x6e, 0x75, 0x6d, 0x73, 0x32, 0x4c, 0x0a, 0x0b, 0x53, 0x6f, 0x72, 0x74, 0x53,
	0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12, 0x3d, 0x0a, 0x04, 0x53, 0x6f, 0x72, 0x74, 0x12, 0x18,
	0x2e, 0x73, 0x6f, 0x72, 0x74, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2e, 0x53, 0x6f, 0x72,
	0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x19, 0x2e, 0x73, 0x6f, 0x72, 0x74, 0x53,
	0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2e, 0x53, 0x6f, 0x72, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f,
	0x6e, 0x73, 0x65, 0x22, 0x00, 0x42, 0x12, 0x5a, 0x10, 0x73, 0x74, 0x75, 0x62, 0x2f, 0x73, 0x6f,
	0x72, 0x74, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x33,
}

var (
	file_sortService_proto_rawDescOnce sync.Once
	file_sortService_proto_rawDescData = file_sortService_proto_rawDesc
)

func file_sortService_proto_rawDescGZIP() []byte {
	file_sortService_proto_rawDescOnce.Do(func() {
		file_sortService_proto_rawDescData = protoimpl.X.CompressGZIP(file_sortService_proto_rawDescData)
	})
	return file_sortService_proto_rawDescData
}

var file_sortService_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_sortService_proto_goTypes = []interface{}{
	(*SortRequest)(nil),  // 0: sortService.SortRequest
	(*SortResponse)(nil), // 1: sortService.SortResponse
}
var file_sortService_proto_depIdxs = []int32{
	0, // 0: sortService.SortService.Sort:input_type -> sortService.SortRequest
	1, // 1: sortService.SortService.Sort:output_type -> sortService.SortResponse
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_sortService_proto_init() }
func file_sortService_proto_init() {
	if File_sortService_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_sortService_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SortRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_sortService_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SortResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_sortService_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_sortService_proto_goTypes,
		DependencyIndexes: file_sortService_proto_depIdxs,
		MessageInfos:      file_sortService_proto_msgTypes,
	}.Build()
	File_sortService_proto = out.File
	file_sortService_proto_rawDesc = nil
	file_sortService_proto_goTypes = nil
	file_sortService_proto_depIdxs = nil
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConnInterface

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion6

// SortServiceClient is the client API for SortService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type SortServiceClient interface {
	Sort(ctx context.Context, in *SortRequest, opts ...grpc.CallOption) (*SortResponse, error)
}

type sortServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewSortServiceClient(cc grpc.ClientConnInterface) SortServiceClient {
	return &sortServiceClient{cc}
}

func (c *sortServiceClient) Sort(ctx context.Context, in *SortRequest, opts ...grpc.CallOption) (*SortResponse, error) {
	out := new(SortResponse)
	err := c.cc.Invoke(ctx, "/sortService.SortService/Sort", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// SortServiceServer is the server API for SortService service.
type SortServiceServer interface {
	Sort(context.Context, *SortRequest) (*SortResponse, error)
}

// UnimplementedSortServiceServer can be embedded to have forward compatible implementations.
type UnimplementedSortServiceServer struct {
}

func (*UnimplementedSortServiceServer) Sort(context.Context, *SortRequest) (*SortResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Sort not implemented")
}

func RegisterSortServiceServer(s *grpc.Server, srv SortServiceServer) {
	s.RegisterService(&_SortService_serviceDesc, srv)
}

func _SortService_Sort_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SortRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SortServiceServer).Sort(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/sortService.SortService/Sort",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SortServiceServer).Sort(ctx, req.(*SortRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _SortService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "sortService.SortService",
	HandlerType: (*SortServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Sort",
			Handler:    _SortService_Sort_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "sortService.proto",
}
